version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:30"
    commit-message:
      prefix: "#27 - "
    open-pull-requests-limit: 1
