version: "3.7"

services:
  node:
    container_name: blumilkpl-node
    image: node:20-alpine3.17
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
    restart: always
    ports:
      - ${EXTERNAL_NODE_PORT:-14380}:${EXTERNAL_NODE_PORT:-14380}
    tty: true
