version: "3.8"

networks:
  traefik-proxy:
    external: true
  blumilk-website-beta:
    driver: bridge

volumes:
  blumilk-website-beta-pgsql-data:
    name: blumilk-website-beta-pgsql-data
  blumilk-website-beta-redis-data:
    name: blumilk-website-beta-redis-data

services:
  blumilk-website-beta-app:
    image: registry.blumilk.pl/website/website:beta
    container_name: blumilk-website-beta-app
    pull_policy: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blumilk-website-beta-app.rule=Host(`${BLUMILK_WEBSITE_BETA_HOST_NAME}`)"
      - "traefik.http.routers.blumilk-website-beta-app.entrypoints=websecure"
      - "traefik.http.routers.blumilk-website-beta-app.tls=true"
      - "traefik.http.routers.blumilk-website-beta-app.tls.certresolver=lets-encrypt-resolver"
      - "traefik.http.routers.blumilk-website-beta-app.middlewares=response-gzip-compress@file"
    depends_on:
      blumilk-website-beta-database:
        condition: service_healthy
      blumilk-website-beta-redis:
        condition: service_healthy
    working_dir: /application
    volumes:
      - ./.env:/application/.env:ro
    networks:
      - blumilk-website-beta
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .deployment

  blumilk-website-beta-database:
    image: postgres:16.1-alpine3.18
    container_name: blumilk-website-beta-database
    environment:
      - PGPASSWORD=${DOCKER_BLUMILK_WEBSITE_BETA_DB_ROOT_PASSWORD:? variable DOCKER_BLUMILK_WEBSITE_BETA_DB_ROOT_PASSWORD not set}
      - POSTGRES_DB=${DOCKER_BLUMILK_WEBSITE_BETA_DB_DATABASE:? variable DOCKER_BLUMILK_WEBSITE_BETA_DB_DATABASE not set}
      - POSTGRES_USER=${DOCKER_BLUMILK_WEBSITE_BETA_DB_USERNAME:? variable DOCKER_BLUMILK_WEBSITE_BETA_DB_USERNAME not set}
      - POSTGRES_PASSWORD=${DOCKER_BLUMILK_WEBSITE_BETA_DB_PASSWORD:? variable DOCKER_BLUMILK_WEBSITE_BETA_DB_PASSWORD not set}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DOCKER_BLUMILK_WEBSITE_BETA_DB_DATABASE} --username ${DOCKER_BLUMILK_WEBSITE_BETA_DB_USERNAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - blumilk-website-beta-pgsql-data:/var/lib/postgresql/data
    networks:
      - blumilk-website-beta
    restart: unless-stopped

  blumilk-website-beta-redis:
    image: redis:7.0-alpine3.16@sha256:2700d5097763fda285c463f4eefc3d0730a2df2a9d48e66707b19d5a5e5f23d4
    container_name: blumilk-website-beta-redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - blumilk-website-beta-redis-data:/data
    networks:
      - blumilk-website-beta
    restart: unless-stopped
