<section class="mx-[10%] lg:mx-[15%] 2xl:max-w-7xl 2xl:mx-auto space-y-10 py-20 text-center">
    <h2 class="text-3xl md:text-4xl lg:text-5xl font-semibold pb-8"> Kluczowe funkcjonalności </h2>
    <div class="grid md:grid-cols-2 xl:grid-cols-6 gap-4 2xl:gap-12 place-items-center xl:place-items-stretch">
        <x-tile image="{{ asset('graphics/services/window.svg') }}"
                alt="benefit-1"
                title="{{ __('content.home.section_3.tile_1.title') }}"
                description="{{ __('content.home.section_3.tile_1.subtitle') }}"
                class="xl:col-span-2 size-full"/>
        <x-tile image="{{ asset('graphics/services/file.svg') }}"
                alt="benefit-1"
                title="{{ __('content.home.section_3.tile_2.title') }}"
                description="{{ __('content.home.section_3.tile_2.subtitle') }}"
                class="xl:col-span-2 size-full"/>
        <x-tile image="{{ asset('graphics/services/web.svg') }}"
                alt="benefit-1"
                title="{{ __('content.home.section_3.tile_3.title') }}"
                description="{{ __('content.home.section_3.tile_3.subtitle') }}"
                class="xl:col-span-2 size-full"/>
        <x-tile image="{{ asset('graphics/services/analyse.svg') }}"
                alt="benefit-1"
                title="{{ __('content.home.section_3.tile_4.title') }}"
                description="{{ __('content.home.section_3.tile_4.subtitle') }}"
                class="xl:col-span-3 xl:max-w-[395px] xl:place-self-end size-full"/>
        <x-tile image="{{ asset('graphics/services/gallery.svg') }}"
                alt="benefit-1"
                title="{{ __('content.home.section_3.tile_5.title') }}"
                description="{{ __('content.home.section_3.tile_5.subtitle') }}"
                class="md:col-span-2 xl:col-span-3 xl:max-w-[395px] xl:place-self-start size-full"/>
    </div>
</section>
