name: "Checking app: testing and linting JS"

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  test-and-lint-js:
    name: Test & lint JS codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=node-version depName=node
      NODE_VERSION: 22.23.2

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 # https://github.com/actions/checkout

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0 # https://github.com/actions/cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0 # https://github.com/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Instal npm dependencies
        run: npm clean-install

      - name: Run JS linter
        run: npm run lint
