name: "Checking app: testing and linting"

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node14.17.0-chrome88-ff89

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Test application
        run: npm run test

      - name: Lint codebase
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm build
          start: npm start
          browser: chrome
          wait-on: http://localhost:5000
          headless: true

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
