name: "Checking app: testing and linting JS"

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  test-and-lint-js:
    name: Test & lint JS codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1 # https://github.com/actions/checkout

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0 # https://github.com/actions/cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0 # https://github.com/actions/setup-node
        with:
          node-version: 22.22.2

      - name: Instal npm dependencies
        run: npm clean-install

      - name: Run JS linter
        run: npm run lint
